Repository f-lab-edu/event-recommender-festa, pull requests merged in 2020-11, with the labels that each got.

#35 checkLoginStatusAop의 중복코드 제거
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/controller/MemberController.java
Labels: Completed

#32 세션 유저아이디 조회 기능 & 권한에 따른 로그인 여부확인 기능 추가
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/controller/MemberController.java
Labels: Completed, Ready for Merge

#30 회원정보 조회 기능 추가
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: Completed, Ready for Merge

#39 회원 비밀번호 변경 기능
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/common/LoginUserIdResolver.java
  src/main/java/com/festa/common/commonService/CurrentLoginUserId.java
  src/main/java/com/festa/config/WebConfig.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: Asking for review, Refactoring

#28 로그인 여부 확인 중복코드 제거
  pom.xml
  src/main/java/com/festa/FestaApplication.java
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/LoginUserIdResolver.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/CurrentLoginUserId.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/config/WebConfig.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/dto/MemberDTO.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: Completed, Ready for Merge

#33 [#20]feat: 회원 탈퇴 기능
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: Completed

#24 [#22] 비밀번호 변경 알림 서비스 추가
  .gitignore
  pom.xml
  src/main/java/com/festa/FestaApplication.java
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/LoginUserIdResolver.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/CurrentLoginUserId.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/config/FirebaseConfig.java
  src/main/java/com/festa/config/WebConfig.java
  src/main/java/com/festa/controller/AlertController.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/AlertDAO.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/dto/AlertDTO.java
  src/main/java/com/festa/dto/MemberDTO.java
  src/main/java/com/festa/service/AlertService.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/mapper/AlertMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: Asking for review

#21 [#19] 회원정보 수정 기능
  .gitignore
  pom.xml
  src/main/java/com/festa/FestaApplication.java
  src/main/java/com/festa/aop/CheckLoginStatus.java
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/LoginUserIdResolver.java
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/UserLevel.java
  src/main/java/com/festa/common/commonService/CurrentLoginUserId.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/config/FirebaseConfig.java
  src/main/java/com/festa/config/WebConfig.java
  src/main/java/com/festa/controller/AlertController.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/AlertDAO.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/dto/AlertDTO.java
  src/main/java/com/festa/dto/MemberDTO.java
  src/main/java/com/festa/service/AlertService.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/mapper/AlertMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: Waiting

#44 [#42] members 테이블 memberWithdraw 추가
  src/main/resources/mapper/MemberMapper.xml
Labels: Asking for review

#38 [#13]feat:Redis session storage 연동
  pom.xml
  src/main/java/com/festa/config/RedisConfig.java
  src/main/resources/application.properties
Labels: Asking for review
