Repository f-lab-edu/event-recommender-festa, pull requests merged in 2020-12, with the labels that each got.

#47 사용자 이벤트 접수 기능
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/model/Participants.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
Labels: Asking for review

#43 리스트형 이벤트 목록 조회기능 추가
  src/main/java/com/festa/common/ResponseEntityConstants.java
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/model/PageInfo.java
  src/main/java/com/festa/model/Participants.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
Labels: Completed, Ready for Merge

#48 feat:members 테이블 사용자 번호 컬럼 추가로 인한 수정
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/LoginUserIdResolver.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/commonService/CurrentLoginUserNo.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/controller/AlertController.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/AlertDAO.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/dto/MemberDTO.java
  src/main/java/com/festa/service/AlertService.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/AlertMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: Asking for review

#53 테이블 변경으로 인한 수정(변경내역은 설명 참조)
  src/main/java/com/festa/aop/CheckLoginStatusAop.java
  src/main/java/com/festa/common/LoginUserNoResolver.java
  src/main/java/com/festa/common/SessionLogin.java
  src/main/java/com/festa/common/commonService/LoginService.java
  src/main/java/com/festa/config/DatabaseConfig.java
  src/main/java/com/festa/config/WebConfig.java
  src/main/java/com/festa/controller/AlertController.java
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/AlertDAO.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/dto/AlertDTO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/dto/MemberDTO.java
  src/main/java/com/festa/service/AlertService.java
  src/main/java/com/festa/service/EventService.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/AlertMapper.xml
  src/main/resources/mapper/EventsMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: Completed, Ready for Merge

#46 feat:사용자(회원+주최자) 이벤트 상세보기 기능
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
Labels: Asking for review, conflict

#60 카테고리별 조회 기능 추가 & 캐싱 적용
  src/main/java/com/festa/FestaApplication.java
  src/main/java/com/festa/common/RedisCacheKey.java
  src/main/java/com/festa/config/RedisConfig.java
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
Labels: Asking for review

#68 주최자 이벤트 등록 기능
  src/main/java/com/festa/config/DatabaseConfig.java
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
Labels: Asking for review, conflict
