Repository f-lab-edu/event-recommender-festa, pull requests merged in 2021-06, with the labels that each got.

#135 이벤트 관련 쿼리 수정
  src/main/resources/mapper/EventsMapper.xml
Labels: Asking for review, In Progress

#137 이벤트 신청 취소 기능 수정
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
  src/test/java/com/festa/service/EventServiceTest.java
Labels: In Progress

#145 EventDAO 파라미터 수정
  src/main/java/com/festa/dao/EventDAO.java
  src/main/resources/mapper/EventsMapper.xml
Labels: In Progress

#143 이벤트 신청 취소 기능 로직 수정
  src/main/java/com/festa/dao/EventDAO.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/mapper/EventsMapper.xml
  src/test/java/com/festa/service/EventServiceTest.java
Labels: In Progress

#141 MemberDAO 파라미터 수정
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/resources/mapper/MemberMapper.xml
Labels: In Progress

#139 비밀번호 수정 기능 수정
  src/main/java/com/festa/controller/MemberController.java
  src/main/java/com/festa/dao/MemberDAO.java
  src/main/java/com/festa/model/MemberNewPw.java
  src/main/java/com/festa/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
  src/test/java/com/festa/MemberControllerTests.java
  src/test/java/com/festa/MemberServiceTests.java
Labels: Ready for Merge

#147 API URI 수정
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/controller/MemberController.java
  src/test/java/com/festa/MemberControllerTests.java
Labels: Asking for review

#148 이벤트 추가 시 사진 추가 기능
  pom.xml
  src/main/java/com/festa/common/S3ImageUploader.java
  src/main/java/com/festa/common/commonService/ImageUploader.java
  src/main/java/com/festa/controller/EventController.java
  src/main/java/com/festa/dto/EventDTO.java
  src/main/java/com/festa/exception/ImageUploadException.java
  src/main/java/com/festa/service/EventService.java
  src/main/resources/application.properties
  src/main/resources/mapper/EventsMapper.xml
  src/test/java/com/festa/service/EventServiceTest.java
Labels: In Progress
